import { type GeoZonesI, type FrenchZonesI } from "@/interfaces/geoZonesI";

export const geoZones: GeoZonesI = {
  regions: [
    "Auvergne-Rhône-Alpes",
    "Bourgogne-Franche-Comté",
    "Bretagne",
    "Centre-Val de Loire",
    "Corse",
    "Grand Est",
    "Guadeloupe",
    "Guyane",
    "Hauts-de-France",
    "Île-de-France",
    "La Réunion",
    "Martinique",
    "Mayotte",
    "Normandie",
    "Nouvelle-Aquitaine",
    "Occitanie",
    "Pays de la Loire",
    "Provence-Alpes-Côte d'Azur"
  ],
  departments: [
    "Ain",
    "Aisne",
    "Allier",
    "Alpes-de-Haute-Provence",
    "Hautes-Alpes",
    "Alpes-Maritimes",
    "Ardèche",
    "Ardennes",
    "Ariège",
    "Aube",
    "Aude",
    "Aveyron",
    "Bouches-du-Rhône",
    "Calvados",
    "Cantal",
    "Charente",
    "Charente-Maritime",
    "Cher",
    "Corrèze",
    "Côte-d'Or",
    "Côtes-d'Armor",
    "Creuse",
    "Dordogne",
    "Doubs",
    "Drôme",
    "Eure",
    "Eure-et-Loir",
    "Finistère",
    "Corse-du-Sud",
    "Haute-Corse",
    "Gard",
    "Haute-Garonne",
    "Gers",
    "Gironde",
    "Hérault",
    "Ille-et-Vilaine",
    "Indre",
    "Indre-et-Loire",
    "Isère",
    "Jura",
    "Landes",
    "Loir-et-Cher",
    "Loire",
    "Haute-Loire",
    "Loire-Atlantique",
    "Loiret",
    "Lot",
    "Lot-et-Garonne",
    "Lozère",
    "Maine-et-Loire",
    "Manche",
    "Marne",
    "Haute-Marne",
    "Mayenne",
    "Meurthe-et-Moselle",
    "Meuse",
    "Morbihan",
    "Moselle",
    "Nièvre",
    "Nord",
    "Oise",
    "Orne",
    "Pas-de-Calais",
    "Puy-de-Dôme",
    "Pyrénées-Atlantiques",
    "Hautes-Pyrénées",
    "Pyrénées-Orientales",
    "Bas-Rhin",
    "Haut-Rhin",
    "Rhône",
    "Haute-Saône",
    "Saône-et-Loire",
    "Sarthe",
    "Savoie",
    "Haute-Savoie",
    "Paris",
    "Seine-Maritime",
    "Seine-et-Marne",
    "Yvelines",
    "Deux-Sèvres",
    "Somme",
    "Tarn",
    "Tarn-et-Garonne",
    "Var",
    "Vaucluse",
    "Vendée",
    "Vienne",
    "Haute-Vienne",
    "Vosges",
    "Yonne",
    "Territoire de Belfort",
    "Essonne",
    "Hauts-de-Seine",
    "Seine-Saint-Denis",
    "Val-de-Marne",
    "Val-d'Oise",
    "Guadeloupe",
    "Martinique",
    "Guyane",
    "La Réunion",
    "Mayotte"
  ],
  postalCodes: [
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "2A",
    "2B",
    "30",
    "31",
    "32",
    "33",
    "34",
    "35",
    "36",
    "37",
    "38",
    "39",
    "40",
    "41",
    "42",
    "43",
    "44",
    "45",
    "46",
    "47",
    "48",
    "49",
    "50",
    "51",
    "52",
    "53",
    "54",
    "55",
    "56",
    "57",
    "58",
    "59",
    "60",
    "61",
    "62",
    "63",
    "64",
    "65",
    "66",
    "67",
    "68",
    "69",
    "70",
    "71",
    "72",
    "73",
    "74",
    "75",
    "76",
    "77",
    "78",
    "79",
    "80",
    "81",
    "82",
    "83",
    "84",
    "85",
    "86",
    "87",
    "88",
    "89",
    "90",
    "91",
    "92",
    "93",
    "94",
    "95",
    "971",
    "972",
    "973",
    "974",
    "976"
  ]
};

export const frenchZones: FrenchZonesI = {
  regions: {
    "Auvergne-Rhône-Alpes": {
      "regionsDepartments": ["Ain", "Allier", "Ardèche", "Cantal", "Drôme", "Isère", "Loire", "Haute-Loire", "Puy-de-Dôme", "Rhône", "Savoie", "Haute-Savoie"],
      "regionsPostalsCode": ["01", "03", "07", "15", "26", "38", "42", "43", "63", "69", "73", "74"]
    },
    "Bourgogne-Franche-Comté": {
      "regionsDepartments": ["Côte-d'Or", "Doubs", "Jura", "Nièvre", "Haute-Saône", "Saône-et-Loire", "Yonne", "Territoire de Belfort"],
      "regionsPostalsCode": ["21", "25", "39", "58", "70", "71", "89", "90"]
    },
    "Bretagne": {
      "regionsDepartments": ["Côtes-d'Armor", "Finistère", "Ille-et-Vilaine", "Morbihan"],
      "regionsPostalsCode": ["22", "29", "35", "56"]
    },
    "Centre-Val de Loire": {
      "regionsDepartments": ["Cher", "Eure-et-Loir", "Indre", "Indre-et-Loire", "Loir-et-Cher", "Loiret"],
      "regionsPostalsCode": ["18", "28", "36", "37", "41", "45"]
    },
    "Corse": {
      "regionsDepartments": ["Corse-du-Sud", "Haute-Corse"],
      "regionsPostalsCode": ["2A", "2B"]
    },
    "Grand Est": {
      "regionsDepartments": ["Ardennes", "Aube", "Marne", "Haute-Marne", "Meurthe-et-Moselle", "Meuse", "Moselle", "Bas-Rhin", "Haut-Rhin", "Vosges"],
      "regionsPostalsCode": ["08", "10", "51", "52", "54", "55", "57", "67", "68", "88"]
    },
    "Guadeloupe": {
      "regionsDepartments": ["Guadeloupe"],
      "regionsPostalsCode": ["971"]
    },
    "Guyane": {
      "regionsDepartments": ["Guyane"],
      "regionsPostalsCode": ["973"]
    },
    "Hauts-de-France": {
      "regionsDepartments": ["Aisne", "Nord", "Oise", "Pas-de-Calais", "Somme"],
      "regionsPostalsCode": ["02", "59", "60", "62", "80"]
    },
    "Île-de-France": {
      "regionsDepartments": ["Paris", "Seine-et-Marne", "Yvelines", "Essonne", "Hauts-de-Seine", "Seine-Saint-Denis", "Val-de-Marne", "Val-d'Oise"],
      "regionsPostalsCode": ["75", "77", "78", "91", "92", "93", "94", "95"]
    },
    "La Réunion": {
      "regionsDepartments": ["La Réunion"],
      "regionsPostalsCode": ["974"]
    },
    "Martinique": {
      "regionsDepartments": ["Martinique"],
      "regionsPostalsCode": ["972"]
    },
    "Mayotte": {
      "regionsDepartments": ["Mayotte"],
      "regionsPostalsCode": ["976"]
    },
    "Normandie": {
      "regionsDepartments": ["Calvados", "Eure", "Manche", "Orne", "Seine-Maritime"],
      "regionsPostalsCode": ["14", "27", "50", "61", "76"]
    },
    "Nouvelle-Aquitaine": {
      "regionsDepartments": ["Charente", "Charente-Maritime", "Corrèze", "Creuse", "Dordogne", "Gironde", "Landes", "Lot-et-Garonne", "Pyrénées-Atlantiques", "Deux-Sèvres", "Vienne", "Haute-Vienne"],
      "regionsPostalsCode": ["16", "17", "19", "23", "24", "33", "40", "47", "64", "79", "86", "87"]
    },
    "Occitanie": {
      "regionsDepartments": ["Ariège", "Aude", "Aveyron", "Gard", "Haute-Garonne", "Gers", "Hérault", "Lot", "Lozère", "Hautes-Pyrénées", "Pyrénées-Orientales", "Tarn", "Tarn-et-Garonne"],
      "regionsPostalsCode": ["09", "11", "12", "30", "31", "32", "34", "46", "48", "65", "66", "81", "82"]
    },
    "Pays de la Loire": {
      "regionsDepartments": ["Loire-Atlantique", "Maine-et-Loire", "Mayenne", "Sarthe", "Vendée"],
      "regionsPostalsCode": ["44", "49", "53", "72", "85"]
    },
    "Provence-Alpes-Côte d'Azur": {
      "regionsDepartments": ["Alpes-de-Haute-Provence", "Hautes-Alpes", "Alpes-Maritimes", "Bouches-du-Rhône", "Var", "Vaucluse"],
      "regionsPostalsCode": ["04", "05", "06", "13", "83", "84"]
    }
  }
};